"""Cedar policy generator for observe mode.

Takes a behavioral profile and generalization rules and emits
Cedar policy text. Pure string templating. No model inference.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any

from apg.config import ObserveGeneralizationConfig
from apg.observe.generalize import (
    CommandGeneralizer,
    GeneralizedRule,
    PathGeneralizer,
)
from apg.observe.profile import AgentProfile


class PolicyGenerator:
    """Generates Cedar policies from observed agent behavior.

    The generated policies represent a least-privilege envelope: they
    permit exactly what was observed and nothing more. Protected patterns
    and dangerous commands are flagged but never auto-permitted.
    """

    def __init__(self, config: ObserveGeneralizationConfig):
        self._path_gen = PathGeneralizer(config)
        self._cmd_gen = CommandGeneralizer(config)
        self._config = config

    def generate(self, profile: AgentProfile, delta: bool = False) -> str:
        """Generate Cedar policy text from an agent profile.

        Args:
            profile: The behavioral profile to convert
            delta: If True, header indicates this is additive to existing policy

        Returns:
            Cedar policy text with inline documentation
        """
        lines: list[str] = []

        # Header
        lines.extend(self._header(profile, delta))
        lines.append("")

        # Generate rules per environment
        for env in sorted(profile.environments):
            lines.append(f"// --- Environment: {env} ---")
            lines.append("")

            # Generate rules per action type
            for action_type in sorted(profile.action_counts.keys()):
                paths = [p for p in profile.resource_paths.get(action_type, set())]
                if not paths:
                    continue

                if action_type == "execute":
                    rules = self._cmd_gen.generalize(paths)
                    lines.extend(self._emit_execute_rules(profile.agent_id, env, rules))
                else:
                    rules = self._path_gen.generalize(paths)
                    lines.extend(self._emit_path_rules(profile.agent_id, action_type, env, rules))

                lines.append("")

        # Recommended forbid rules
        lines.extend(self._recommended_forbids(profile))

        return "\n".join(lines) + "\n"

    def _header(self, profile: AgentProfile, delta: bool) -> list[str]:
        label = "DELTA POLICY" if delta else "AUTO-GENERATED POLICY"
        lines = [
            f"// {'=' * 72}",
            f"// {label} - Generated by APG observe mode",
            f"// {'=' * 72}",
            f"// Agent:              {profile.agent_id}",
            f"// Observation window: {profile.first_seen} to {profile.last_seen}",
            f"// Total calls:        {profile.total_calls}",
            f"// Generated at:       {datetime.now(UTC).isoformat()}",
            f"// Max risk observed:  {profile.max_risk}",
            "//",
        ]
        if delta:
            lines.append("// These rules cover tool calls that were DENIED by current policy.")
            lines.append("// Review each rule. Approve legitimate access. Investigate unexpected access.")
        else:
            lines.append("// Review before applying. Adjust generalization as needed.")
        lines.append(f"// {'=' * 72}")
        return lines

    def _emit_path_rules(
        self,
        agent_id: str,
        action_type: str,
        environment: str,
        rules: list[GeneralizedRule],
    ) -> list[str]:
        """Emit Cedar permit rules for filesystem path patterns."""
        lines: list[str] = []

        # Separate flagged from normal rules
        normal = [r for r in rules if not r.flagged]
        flagged = [r for r in rules if r.flagged]

        if normal:
            # Build provenance comments
            for rule in normal:
                if rule.collapsed:
                    lines.append(
                        f"// Observed {rule.source_count} files "
                        f"(threshold: {self._config.file_collapse_threshold}, collapsed to wildcard)"
                    )
                    lines.append(f"// Files: {', '.join(rule.source_files[:10])}")
                    if len(rule.source_files) > 10:
                        lines.append(f"//   ... and {len(rule.source_files) - 10} more")

            # Build the condition list
            conditions = []
            for rule in normal:
                if rule.collapsed:
                    conditions.append(f'    context.resource_path like "{rule.pattern}"')
                else:
                    conditions.append(f'    context.resource_path == "{rule.pattern}"')

            lines.append("permit(")
            lines.append(f'  principal == Agent::"{agent_id}",')
            lines.append('  action == Action::"toolCall",')
            lines.append("  resource")
            lines.append(") when {")
            lines.append(f'  context.action_type == "{action_type}" &&')
            lines.append(f'  context.environment == "{environment}" &&')
            lines.append("  (")
            lines.append(" ||\n".join(conditions))
            lines.append("  )")
            lines.append("};")

        # Flagged rules as comments
        for rule in flagged:
            lines.append(f"// FLAGGED: observed but not auto-permitted ({rule.flag_reason})")
            lines.append(f"//   path: {rule.pattern}")
            lines.append(f"//   action: {action_type}")
            lines.append(f"//   Uncomment the rule below if this access is legitimate:")
            lines.append(f"// permit(")
            lines.append(f'//   principal == Agent::"{agent_id}",')
            lines.append(f'//   action == Action::"toolCall",')
            lines.append(f"//   resource")
            lines.append(f"// ) when {{")
            lines.append(f'//   context.action_type == "{action_type}" &&')
            lines.append(f'//   context.environment == "{environment}" &&')
            lines.append(f'//   context.resource_path == "{rule.pattern}"')
            lines.append(f"// }};")

        return lines

    def _emit_execute_rules(
        self,
        agent_id: str,
        environment: str,
        rules: list[GeneralizedRule],
    ) -> list[str]:
        """Emit Cedar permit rules for shell command patterns."""
        lines: list[str] = []

        normal = [r for r in rules if not r.flagged]
        flagged = [r for r in rules if r.flagged]

        if normal:
            for rule in normal:
                if rule.collapsed:
                    lines.append(f"// Observed {rule.source_count} commands with prefix '{rule.pattern.rstrip('*')}'")
                    lines.append(f"// Commands: {', '.join(rule.source_files[:5])}")
                    if len(rule.source_files) > 5:
                        lines.append(f"//   ... and {len(rule.source_files) - 5} more")

            conditions = []
            for rule in normal:
                conditions.append(f'    context.resource_path like "{rule.pattern}"')

            lines.append("permit(")
            lines.append(f'  principal == Agent::"{agent_id}",')
            lines.append('  action == Action::"toolCall",')
            lines.append('  resource == Tool::"shell"')
            lines.append(") when {")
            lines.append('  context.action_type == "execute" &&')
            lines.append(f'  context.environment == "{environment}" &&')
            lines.append('  context.risk_level in ["low", "medium"] &&')
            lines.append("  (")
            lines.append(" ||\n".join(conditions))
            lines.append("  )")
            lines.append("};")

        for rule in flagged:
            lines.append(f"// FLAGGED: observed but not auto-permitted ({rule.flag_reason})")
            lines.append(f"//   command: {rule.pattern}")
            lines.append(f"//   This command matched a dangerous pattern. Do NOT permit without review.")

        return lines

    def _recommended_forbids(self, profile: AgentProfile) -> list[str]:
        """Emit recommended forbid rules for patterns never observed."""
        lines = [
            "",
            "// --- Recommended forbid rules ---",
            "// These block actions that were never observed during the window.",
            "",
        ]

        # Forbid prod if never observed in prod
        if "prod" not in profile.environments:
            lines.append(f"// Agent was never observed in prod. Block all prod access.")
            lines.append("forbid(")
            lines.append(f'  principal == Agent::"{profile.agent_id}",')
            lines.append('  action == Action::"toolCall",')
            lines.append("  resource")
            lines.append(") when {")
            lines.append('  context.environment == "prod"')
            lines.append("};")
            lines.append("")

        # Forbid delete if never observed
        if "delete" not in profile.action_counts:
            lines.append(f"// Agent was never observed deleting. Block delete actions.")
            lines.append("forbid(")
            lines.append(f'  principal == Agent::"{profile.agent_id}",')
            lines.append('  action == Action::"toolCall",')
            lines.append("  resource")
            lines.append(") when {")
            lines.append('  context.action_type == "delete"')
            lines.append("};")
            lines.append("")

        # Forbid critical risk if never observed
        if "critical" not in profile.risk_counts:
            lines.append(f"// Agent was never observed at critical risk. Block critical actions.")
            lines.append("forbid(")
            lines.append(f'  principal == Agent::"{profile.agent_id}",')
            lines.append('  action == Action::"toolCall",')
            lines.append("  resource")
            lines.append(") when {")
            lines.append('  context.risk_level == "critical"')
            lines.append("};")
            lines.append("")

        return lines
