"""Auto-discovery of MCP tool mappings.

Connects to AgentGateway's federated tool catalog (or reads a tools/list
JSON dump), classifies each tool using ToolAnnotations, name heuristics,
and input schema analysis, and generates a draft tool_mappings.yaml.

No NLP, no model. Three tiers of deterministic signal:
  1. ToolAnnotations (readOnlyHint, destructiveHint, idempotentHint)
  2. Tool name keyword matching
  3. Input schema field name analysis
"""

from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any

import yaml

logger = logging.getLogger(__name__)


class Confidence(str, Enum):
    HIGH = "high"        # ToolAnnotations present and unambiguous
    MEDIUM = "medium"    # Name heuristic matched
    LOW = "low"          # No strong signal, needs manual review


# ---------------------------------------------------------------------------
# Tier 2: name-based keyword sets
# ---------------------------------------------------------------------------
_READ_KEYWORDS = {"read", "get", "fetch", "list", "search", "find", "show",
                  "view", "query", "browse", "inspect", "describe", "tree",
                  "ls", "dir", "cat", "head", "tail", "grep", "info", "stat",
                  "lookup", "retrieve", "download"}

_WRITE_KEYWORDS = {"write", "create", "update", "edit", "set", "put", "modify",
                   "add", "insert", "append", "patch", "replace", "upload",
                   "save", "store", "push", "commit", "publish", "post"}

_DELETE_KEYWORDS = {"delete", "remove", "destroy", "drop", "truncate", "purge",
                    "erase", "unlink", "revoke", "clear", "wipe"}

_EXECUTE_KEYWORDS = {"run", "execute", "exec", "bash", "shell", "command",
                     "invoke", "call", "start", "launch", "spawn", "eval",
                     "apply", "deploy", "migrate"}

# ---------------------------------------------------------------------------
# Tier 3: input schema field → resource type mapping
# ---------------------------------------------------------------------------
_RESOURCE_FIELD_MAP: dict[str, tuple[str, str]] = {
    # field_name_pattern → (resource_prefix, category)
    "path": ("file:", "filesystem"),
    "file": ("file:", "filesystem"),
    "filepath": ("file:", "filesystem"),
    "file_path": ("file:", "filesystem"),
    "filename": ("file:", "filesystem"),
    "directory": ("dir:", "filesystem"),
    "dir": ("dir:", "filesystem"),
    "folder": ("dir:", "filesystem"),
    "command": ("shell:", "shell"),
    "cmd": ("shell:", "shell"),
    "shell": ("shell:", "shell"),
    "script": ("shell:", "shell"),
    "url": ("url:", "browser"),
    "uri": ("url:", "browser"),
    "href": ("url:", "browser"),
    "endpoint": ("api:", "api"),
    "query": ("sql:", "data"),
    "sql": ("sql:", "data"),
    "table": ("table:", "data"),
    "pattern": ("pattern:", "filesystem"),
    "glob": ("pattern:", "filesystem"),
    "regex": ("pattern:", "filesystem"),
    "selector": ("dom:", "browser"),
}


@dataclass
class DiscoveredMapping:
    """A single tool mapping generated by auto-discovery."""

    tool_name: str
    action_type: str
    resource_field: str | None
    resource_prefix: str
    category: str
    confidence: Confidence
    classification_reason: str
    risk_escalation: list[dict[str, str]] = field(default_factory=list)
    needs_review: bool = False
    review_reason: str = ""

    # Original tool definition for reference
    description: str = ""
    annotations: dict[str, Any] = field(default_factory=dict)

    def to_mapping_dict(self) -> dict[str, Any]:
        """Convert to the format used in tool_mappings.yaml."""
        mapping: dict[str, Any] = {
            "action_type": self.action_type,
            "resource_field": self.resource_field,
            "resource_prefix": self.resource_prefix,
            "category": self.category,
        }
        if self.risk_escalation:
            mapping["risk_escalation"] = self.risk_escalation
        return mapping


class ToolDiscovery:
    """Discovers and classifies MCP tools into APG mappings.

    Classification priority:
      Tier 1 (HIGH):   ToolAnnotations from MCP spec
      Tier 2 (MEDIUM): Tool name keyword matching
      Tier 3 (LOW):    Fallback defaults, flagged for review
    """

    def __init__(self, existing_mappings: dict[str, Any] | None = None):
        self._existing = existing_mappings or {}

    def discover_from_tools_list(self, tools: list[dict[str, Any]]) -> list[DiscoveredMapping]:
        """Classify a list of MCP tool definitions.

        Args:
            tools: List of tool objects from an MCP tools/list response.
                   Each must have at minimum a "name" field.

        Returns:
            List of DiscoveredMapping objects, one per tool.
        """
        results: list[DiscoveredMapping] = []

        for tool in tools:
            name = tool.get("name", "")
            if not name:
                continue

            # Skip tools that already have explicit mappings
            if name in self._existing:
                logger.debug("Skipping '%s': already mapped", name)
                continue

            mapping = self._classify_tool(tool)
            results.append(mapping)

        return results

    def _classify_tool(self, tool: dict[str, Any]) -> DiscoveredMapping:
        """Run the three-tier classification on a single tool."""
        name: str = tool["name"]
        description: str = tool.get("description", "")
        annotations: dict[str, Any] = tool.get("annotations", {})
        input_schema: dict[str, Any] = tool.get("inputSchema", {})

        # Determine resource field and category from schema
        resource_field, resource_prefix, schema_category = self._analyze_schema(input_schema)

        # Tier 1: ToolAnnotations
        tier1_result = self._classify_from_annotations(annotations)
        if tier1_result is not None:
            action_type, reason = tier1_result
            category = schema_category or self._category_from_action(action_type)
            risk = self._risk_from_annotations(annotations, action_type, category)
            return DiscoveredMapping(
                tool_name=name,
                action_type=action_type,
                resource_field=resource_field,
                resource_prefix=resource_prefix or f"{category}:",
                category=category,
                confidence=Confidence.HIGH,
                classification_reason=f"tier1:annotations - {reason}",
                risk_escalation=risk,
                description=description,
                annotations=annotations,
            )

        # Tier 2: Name heuristics
        tier2_result = self._classify_from_name(name)
        if tier2_result is not None:
            action_type, matched_keyword = tier2_result
            category = schema_category or self._category_from_action(action_type)
            risk = self._default_risk_rules(action_type, category)
            return DiscoveredMapping(
                tool_name=name,
                action_type=action_type,
                resource_field=resource_field,
                resource_prefix=resource_prefix or f"{category}:",
                category=category,
                confidence=Confidence.MEDIUM,
                classification_reason=f"tier2:name_keyword '{matched_keyword}' in '{name}'",
                risk_escalation=risk,
                description=description,
                annotations=annotations,
            )

        # Tier 3: No strong signal
        # Try to infer from category if schema gave us something
        action_type = "unknown"
        if schema_category == "shell":
            action_type = "execute"
        elif schema_category in ("filesystem", "browser"):
            action_type = "read"  # conservative default

        return DiscoveredMapping(
            tool_name=name,
            action_type=action_type,
            resource_field=resource_field,
            resource_prefix=resource_prefix or "unknown:",
            category=schema_category or "unknown",
            confidence=Confidence.LOW,
            classification_reason="tier3:no_signal - manual review required",
            needs_review=True,
            review_reason=(
                f"No ToolAnnotations and no recognized keywords in name '{name}'. "
                f"Description: '{description[:100]}'" if description else
                f"No ToolAnnotations, no keywords, and no description for '{name}'."
            ),
            description=description,
            annotations=annotations,
        )

    def _classify_from_annotations(
        self, annotations: dict[str, Any]
    ) -> tuple[str, str] | None:
        """Tier 1: Classify from MCP ToolAnnotations.

        Returns (action_type, reason) or None if annotations are absent/empty.
        """
        if not annotations:
            return None

        read_only = annotations.get("readOnlyHint")
        destructive = annotations.get("destructiveHint")
        idempotent = annotations.get("idempotentHint")

        # All hints are absent (not just False)
        if read_only is None and destructive is None and idempotent is None:
            return None

        if read_only is True:
            return ("read", "readOnlyHint=true")

        if destructive is True:
            return ("delete", "destructiveHint=true")

        # Not read-only, not destructive
        if idempotent is True:
            return ("write", "idempotentHint=true, not readOnly, not destructive")

        # Not read-only, not destructive, not idempotent
        # This is the "mutating, non-idempotent, non-destructive" case
        # Conservative: classify as write
        if read_only is False:
            return ("write", "readOnlyHint=false, no destructive/idempotent hints")

        return None

    def _classify_from_name(self, name: str) -> tuple[str, str] | None:
        """Tier 2: Classify from tool name keywords.

        Tokenizes the name on underscores, hyphens, and camelCase boundaries,
        then checks each token against the keyword sets.

        Returns (action_type, matched_keyword) or None.
        """
        tokens = self._tokenize_name(name)

        # Check in priority order: delete > execute > write > read
        # Delete and execute are checked first because they're higher risk.
        # If we misclassify a delete as a read, the policy is too permissive.
        # If we misclassify a read as a delete, the policy is too restrictive
        # but safe (and the operator will fix it during review).
        for token in tokens:
            if token in _DELETE_KEYWORDS:
                return ("delete", token)

        for token in tokens:
            if token in _EXECUTE_KEYWORDS:
                return ("execute", token)

        for token in tokens:
            if token in _WRITE_KEYWORDS:
                return ("write", token)

        for token in tokens:
            if token in _READ_KEYWORDS:
                return ("read", token)

        return None

    def _tokenize_name(self, name: str) -> list[str]:
        """Split a tool name into lowercase tokens.

        Handles snake_case, kebab-case, and camelCase:
          read_text_file  -> [read, text, file]
          readTextFile    -> [read, text, file]
          list-directory  -> [list, directory]
        """
        # Insert underscore before uppercase letters for camelCase
        s = re.sub(r"([a-z])([A-Z])", r"\1_\2", name)
        # Split on underscore, hyphen, dot, space
        parts = re.split(r"[_\-.\s]+", s)
        return [p.lower() for p in parts if p]

    def _analyze_schema(
        self, schema: dict[str, Any]
    ) -> tuple[str | None, str, str]:
        """Analyze input schema to find resource field and category.

        Returns (resource_field, resource_prefix, category).
        """
        properties = schema.get("properties", {})
        if not properties:
            return None, "", ""

        # Check each property name against known resource field patterns
        for prop_name in properties:
            prop_lower = prop_name.lower()
            for field_pattern, (prefix, category) in _RESOURCE_FIELD_MAP.items():
                if prop_lower == field_pattern or prop_lower.endswith(f"_{field_pattern}"):
                    return prop_name, prefix, category

        # Check required fields as a secondary signal
        required = schema.get("required", [])
        for req in required:
            req_lower = req.lower()
            for field_pattern, (prefix, category) in _RESOURCE_FIELD_MAP.items():
                if req_lower == field_pattern:
                    return req, prefix, category

        return None, "", ""

    def _risk_from_annotations(
        self,
        annotations: dict[str, Any],
        action_type: str,
        category: str,
    ) -> list[dict[str, str]]:
        """Generate risk escalation rules informed by annotations."""
        rules = []

        if annotations.get("destructiveHint"):
            # Tool is explicitly destructive, baseline risk is high
            rules.append({"pattern": ".*", "risk": "high"})

        # Add standard dangerous patterns for execute tools
        if action_type == "execute" or category == "shell":
            rules.extend(self._default_risk_rules(action_type, category))

        return rules

    def _default_risk_rules(
        self, action_type: str, category: str
    ) -> list[dict[str, str]]:
        """Standard risk escalation rules for a given action/category."""
        if action_type == "execute" or category == "shell":
            return [
                {"pattern": "rm -rf", "risk": "critical"},
                {"pattern": "rm -r", "risk": "high"},
                {"pattern": "sudo", "risk": "high"},
                {"pattern": "chmod", "risk": "high"},
                {"pattern": "chown", "risk": "high"},
                {"pattern": r"curl .* \| (sh|bash)", "risk": "critical"},
                {"pattern": "mkfs", "risk": "critical"},
                {"pattern": r"dd if=", "risk": "critical"},
                {"pattern": r"> /dev/", "risk": "critical"},
            ]
        if action_type == "delete":
            return [{"pattern": ".*", "risk": "high"}]
        return []

    def _category_from_action(self, action_type: str) -> str:
        """Infer a default category from the action type."""
        if action_type == "execute":
            return "shell"
        if action_type in ("read", "write", "delete"):
            return "filesystem"
        return "unknown"


# ---------------------------------------------------------------------------
# YAML generation
# ---------------------------------------------------------------------------

def generate_mappings_yaml(
    discovered: list[DiscoveredMapping],
    include_comments: bool = True,
) -> str:
    """Generate tool_mappings.yaml content from discovered mappings.

    Includes provenance comments showing how each tool was classified
    and which ones need manual review.
    """
    lines: list[str] = []

    lines.append("# Tool Mappings - Auto-generated by APG discovery")
    lines.append("# Review all entries, especially those marked NEEDS REVIEW.")
    lines.append("#")

    # Summary
    high = [d for d in discovered if d.confidence == Confidence.HIGH]
    medium = [d for d in discovered if d.confidence == Confidence.MEDIUM]
    low = [d for d in discovered if d.confidence == Confidence.LOW]
    lines.append(f"# Discovered {len(discovered)} tools:")
    lines.append(f"#   {len(high)} high confidence (ToolAnnotations)")
    lines.append(f"#   {len(medium)} medium confidence (name heuristics)")
    lines.append(f"#   {len(low)} low confidence (needs review)")
    lines.append("")
    lines.append("mappings:")

    for d in sorted(discovered, key=lambda x: x.tool_name):
        lines.append("")

        if include_comments:
            lines.append(f"  # Confidence: {d.confidence.value}")
            lines.append(f"  # Reason: {d.classification_reason}")
            if d.description:
                desc = d.description[:120]
                lines.append(f"  # Description: {desc}")
            if d.needs_review:
                lines.append(f"  # *** NEEDS REVIEW: {d.review_reason} ***")

        lines.append(f"  {d.tool_name}:")
        lines.append(f"    action_type: {d.action_type}")

        if d.resource_field:
            lines.append(f"    resource_field: {d.resource_field}")
        else:
            lines.append(f"    resource_field: null")

        lines.append(f"    resource_prefix: \"{d.resource_prefix}\"")
        lines.append(f"    category: {d.category}")

        if d.risk_escalation:
            lines.append(f"    risk_escalation:")
            for rule in d.risk_escalation:
                lines.append(f"      - pattern: \"{rule['pattern']}\"")
                lines.append(f"        risk: {rule['risk']}")

    # Default section
    lines.append("")
    lines.append("# Default for unmapped tools")
    lines.append("default:")
    lines.append("  action_type: unknown")
    lines.append("  resource_field: null")
    lines.append("  resource_prefix: \"unknown:\"")
    lines.append("  category: unknown")
    lines.append("  risk_level: medium")
    lines.append("")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Loading tools from various sources
# ---------------------------------------------------------------------------

def load_tools_from_file(path: str | Path) -> list[dict[str, Any]]:
    """Load MCP tools/list response from a JSON file.

    Accepts either the raw tools/list response:
      {"tools": [...]}

    Or a plain array of tool objects:
      [{"name": "read_file", ...}, ...]
    """
    path = Path(path)
    raw = json.loads(path.read_text(encoding="utf-8"))

    if isinstance(raw, list):
        return raw
    if isinstance(raw, dict) and "tools" in raw:
        return raw["tools"]
    raise ValueError(f"Unrecognized format in {path}. Expected {{'tools': [...]}} or [...].")


async def fetch_tools_from_gateway(
    gateway_url: str,
    mcp_path: str = "/mcp",
) -> list[dict[str, Any]]:
    """Fetch the federated tool list from AgentGateway's MCP endpoint.

    Sends a tools/list JSON-RPC request to AgentGateway and returns
    the tool definitions from the response.
    """
    import httpx

    jsonrpc_request = {
        "jsonrpc": "2.0",
        "id": 1,
        "method": "tools/list",
        "params": {},
    }

    async with httpx.AsyncClient() as client:
        resp = await client.post(
            f"{gateway_url}{mcp_path}",
            json=jsonrpc_request,
            headers={"Content-Type": "application/json"},
            timeout=30.0,
        )
        resp.raise_for_status()
        data = resp.json()

    result = data.get("result", {})
    tools = result.get("tools", [])

    if not tools:
        logger.warning(
            "No tools returned from %s%s. "
            "Ensure MCP servers are connected to AgentGateway.",
            gateway_url, mcp_path,
        )

    return tools
